//设置公共访问url
module.exports={
  //开发环境
  dev:{
    baseUrl:"http://192.168.8.24:3000/wxapp"
  },
  //测试环境
  test:{
    baseUrl:""
  },
  //线上url
  prod:{
    baseUrl:"https://api.jihui88.net/tianma_app/wxapp"
  }
} 