//设置公共访问url
module.exports={
  //开发环境
  dev:{
    baseUrl:"http://192.168.8.24:3000/wxapp"
  },
  //测试环境
  test:{
    baseUrl:"http://42.192.209.104/tianma_app/wxapp"
  },
  //线上url
  prod:{
    baseUrl:"https://tm.nuclearmall.com/tianma_app/wxapp/"
  }
} 